channels:
  - pytorch
  - nvidia
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8.0
  - cudnn=8.8.0
  - pytorch=2.1.1
  - pytorch-cuda=11.8
  - lightning=2.1.2
  - torchmetrics=1.2.1
  - transformers=4.33.3
  - datasets=2.15.0
  - tensorboardx=2.6.2.2
  - pandas=2.1.3
  - torch-optimizer=0.3.0
  - pytest=7.4.4
  - matplotlib=3.8.2
  - rdkit=2023.09.5
  - jpype1=1.5.0
  - pluggy=1.3.0
  - anyio=3.7.1